#!/bin/bash
set -e
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^(src|include)/.*\.(cpp|h)$' || true)
[ -z "$files" ] && exit 0
echo "$files" | xargs clang-format -i
echo "$files" | xargs git add