#!/usr/bin/env bash
# Build UCX + Abseil + NIXL + NCCL deps (+ system protobuf), then the CUDA project
# (transport/cluster benches).
#
#   scripts/build.sh
#   DEPS=/workspace/deps CMAKE_CUDA_ARCHITECTURES=80 scripts/build.sh
#   SKIP_APT=1 scripts/build.sh          # skip apt/pip package installs
#   SMOKE_ONLY=1 scripts/build.sh        # only run the NIXL smoke (needs prior build)
#
# After a successful build:
#   source "$DEPS/env.sh"
#   ./build-cuda/benchmarks/transport_bench ...
#
# Knobs:
#   DEPS                      dependency install prefix (default: <repo>/deps)
#   UCX_BRANCH                UCX git tag/branch (v1.19.0)
#   ABSL_TAG                  Abseil git tag (20250814.0)
#   CMAKE_CUDA_ARCHITECTURES  e.g. 75 (T4), 80 (A100), 90 (H100); auto from nvidia-smi if unset
#   BUILD_DIR                 cmake build dir (build-cuda)
#   TARGETS                   cmake targets (transport_bench cluster_bench)
#   SKIP_APT                  1 = skip apt-get / pip bootstrap
#   SKIP_SMOKE                1 = skip NIXL smoke at the end
#   FORCE_REBUILD_DEPS        1 = wipe and rebuild UCX/Abseil/NIXL regardless of .ref/.tag

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPS="${DEPS:-$ROOT/deps}"
UCX_PREFIX="${UCX_PREFIX:-$DEPS/ucx}"
NIXL_PREFIX="${NIXL_PREFIX:-$DEPS/nixl}"
ABSL_PREFIX="${ABSL_PREFIX:-$DEPS/absl}"
SRC="${SRC:-$DEPS/src}"
UCX_BRANCH="${UCX_BRANCH:-v1.19.0}"
ABSL_TAG="${ABSL_TAG:-20250814.0}"
BUILD_DIR="${BUILD_DIR:-$ROOT/build-cuda}"
TARGETS="${TARGETS:-transport_bench cluster_bench}"
SKIP_APT="${SKIP_APT:-0}"
SKIP_SMOKE="${SKIP_SMOKE:-0}"
SMOKE_ONLY="${SMOKE_ONLY:-0}"
FORCE_REBUILD_DEPS="${FORCE_REBUILD_DEPS:-0}"

log() { printf '+ %s\n' "$*"; }

detect_cuda_arch() {
  if [[ -n "${CMAKE_CUDA_ARCHITECTURES:-}" ]]; then
    echo "$CMAKE_CUDA_ARCHITECTURES"
    return
  fi
  local cap
  cap="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 | tr -d ' ' || true)"
  if [[ "$cap" =~ ^([0-9]+)\.([0-9]+)$ ]]; then
    echo "${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
    return
  fi
  # Safe default for older cards; override with CMAKE_CUDA_ARCHITECTURES=...
  echo "75"
}

detect_cuda_home() {
  if [[ -n "${CUDA_HOME:-}" && -d "$CUDA_HOME" ]]; then
    echo "$CUDA_HOME"
    return
  fi
  if [[ -d /usr/local/cuda ]]; then
    echo /usr/local/cuda
    return
  fi
  dirname "$(dirname "$(readlink -f "$(command -v nvcc)")")"
}

write_env_sh() {
  local nccl_root="$1" plugin_dir="$2"
  cat > "$DEPS/env.sh" <<EOF
# Generated by scripts/build.sh — source before running benches.
export UCX_ROOT="$UCX_PREFIX"
export NIXL_ROOT="$NIXL_PREFIX"
export ABSL_ROOT="$ABSL_PREFIX"
export NCCL_ROOT="$nccl_root"
export NIXL_PLUGIN_DIR="$plugin_dir"
export CUDA_HOME="${CUDA_HOME}"
export LD_LIBRARY_PATH="$NIXL_PREFIX/lib:$plugin_dir:$UCX_PREFIX/lib:$UCX_PREFIX/lib/ucx:$ABSL_PREFIX/lib:$nccl_root/lib:\${LD_LIBRARY_PATH:-}"
export PKG_CONFIG_PATH="$ABSL_PREFIX/lib/pkgconfig:$UCX_PREFIX/lib/pkgconfig:\${PKG_CONFIG_PATH:-}"
export CMAKE_PREFIX_PATH="$ABSL_PREFIX:$NIXL_PREFIX:\${CMAKE_PREFIX_PATH:-}"
EOF
}

run_smoke() {
  local tls="$1" out
  rm -rf /tmp/nixl_smoke
  if [[ -n "$tls" ]]; then export UCX_TLS="$tls"; else unset UCX_TLS || true; fi
  out="$("$BUILD_DIR/benchmarks/transport_bench" \
        --device GPU --backends nixl --min-mb 1 --max-mb 1 --iters 1 --warmup 0 \
        --modes uni --out-dir /tmp/nixl_smoke 2>&1)" || { echo "$out" | tail -30; return 1; }
  if echo "$out" | grep -q "setup failed"; then echo "$out" | tail -30; return 1; fi
  grep -qi nixl /tmp/nixl_smoke/transport.csv
}

if [[ "$SMOKE_ONLY" == "1" ]]; then
  # shellcheck disable=SC1091
  source "$DEPS/env.sh"
  log "smoke only (sourced $DEPS/env.sh)"
  for tls in "" "self,tcp,sm,cuda_copy,cuda_ipc" "self,tcp,sm,cuda_copy"; do
    log "UCX_TLS='${tls:-<auto>}'"
    if run_smoke "$tls"; then
      echo "NIXL smoke OK (UCX_TLS='${tls:-<auto>}')"
      head -5 /tmp/nixl_smoke/transport.csv
      exit 0
    fi
  done
  echo "NIXL smoke FAILED"
  exit 1
fi

mkdir -p "$SRC"
cd "$ROOT"

CMAKE_CUDA_ARCHITECTURES="$(detect_cuda_arch)"
CUDA_HOME="$(detect_cuda_home)"
log "ROOT=$ROOT"
log "DEPS=$DEPS"
log "CUDA_HOME=$CUDA_HOME"
log "CMAKE_CUDA_ARCHITECTURES=$CMAKE_CUDA_ARCHITECTURES"

# ---------- 1) Rust (tokenizers_cpp) ----------
if ! command -v cargo >/dev/null 2>&1; then
  if [[ -f "$HOME/.cargo/env" ]]; then
    # shellcheck disable=SC1091
    source "$HOME/.cargo/env"
  else
    log "installing rustup"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    # shellcheck disable=SC1091
    source "$HOME/.cargo/env"
  fi
fi
rustc --version

# ---------- 2) System packages ----------
if [[ "$SKIP_APT" != "1" ]]; then
  export DEBIAN_FRONTEND=noninteractive
  if command -v apt-get >/dev/null 2>&1; then
    apt-get update -qq || true
    apt-get install -y -qq \
      build-essential autoconf automake libtool pkg-config \
      cmake ninja-build git curl \
      libnuma-dev libgflags-dev \
      protobuf-compiler libprotobuf-dev \
      python3-pip python3-venv || true
    # Ubuntu's Abseil is too old for NIXL; never use it.
    apt-get remove -y -qq libabsl-dev libabsl20210324 2>/dev/null || true
  fi
  pip3 install -q --upgrade meson ninja pybind11
fi

# CMakeLists.txt pins Protobuf_PROTOC_EXECUTABLE to /usr/bin/protoc and
# find_package(Protobuf REQUIRED) — need the system packages above.
if ! command -v protoc >/dev/null 2>&1; then
  echo "ERROR: protoc not found (install protobuf-compiler, or unset SKIP_APT)"
  exit 1
fi
log "protoc: $(command -v protoc) ($(protoc --version 2>/dev/null || echo '?'))"

# ---------- 3) NCCL (pip wheel) ----------
pip3 install -q nvidia-nccl-cu12
NCCL_ROOT="$(python3 - <<'PY'
from pathlib import Path
import importlib.util
spec = importlib.util.find_spec("nvidia.nccl")
if spec is None or not spec.submodule_search_locations:
    raise SystemExit("nvidia.nccl not found after pip install")
print(Path(spec.submodule_search_locations[0]))
PY
)"
if [[ ! -e "$NCCL_ROOT/lib/libnccl.so" ]]; then
  ln -sf "$(ls "$NCCL_ROOT/lib"/libnccl.so.* | head -1)" "$NCCL_ROOT/lib/libnccl.so"
fi
log "NCCL_ROOT=$NCCL_ROOT"

# ---------- 4) CUDA link shims (containers often lack unversioned .so names) ----------
CUDA_SHIM="$DEPS/cuda_shim"
mkdir -p "$CUDA_SHIM"
LIBCUDA="$(ldconfig -p | awk '/libcuda\.so\.1 /{ if(!f){print $NF; f=1} }')"
test -n "$LIBCUDA" || { echo "ERROR: libcuda.so.1 not found (is the GPU visible?)"; exit 1; }
ln -sf "$LIBCUDA" "$CUDA_SHIM/libcuda.so"
LIBNVML="$(ldconfig -p | awk '/libnvidia-ml\.so\.1 /{ if(!f){print $NF; f=1} }')"
if [[ -z "$LIBNVML" ]]; then
  LIBNVML="$(ls "$CUDA_HOME"/lib64/stubs/libnvidia-ml.so 2>/dev/null | head -1 || true)"
fi
test -n "$LIBNVML" || { echo "ERROR: libnvidia-ml not found"; exit 1; }
ln -sf "$LIBNVML" "$CUDA_SHIM/libnvidia-ml.so"
export LIBRARY_PATH="$CUDA_SHIM:${LIBRARY_PATH:-}"
log "libcuda shim: $CUDA_SHIM/libcuda.so -> $LIBCUDA"
log "libnvidia-ml shim: $CUDA_SHIM/libnvidia-ml.so -> $LIBNVML"

if [[ "$FORCE_REBUILD_DEPS" == "1" ]]; then
  log "FORCE_REBUILD_DEPS=1 -> wiping UCX/Abseil/NIXL"
  rm -rf "$UCX_PREFIX" "$ABSL_PREFIX" "$NIXL_PREFIX" \
         "$SRC/ucx" "$SRC/abseil-cpp" "$SRC/nixl/build"
fi

if [[ "$(cat "$UCX_PREFIX/.ref" 2>/dev/null || true)" != "$UCX_BRANCH" ]]; then
  log "UCX ref changed/missing -> rebuilding UCX and NIXL"
  rm -rf "$UCX_PREFIX" "$SRC/ucx" "$NIXL_PREFIX" "$SRC/nixl/build"
fi

# ---------- 5) UCX (CUDA-enabled, intra-node) ----------
if [[ ! -f "$UCX_PREFIX/lib/libucp.so" ]]; then
  if [[ ! -d "$SRC/ucx/.git" ]]; then
    git clone --depth 1 --branch "$UCX_BRANCH" https://github.com/openucx/ucx.git "$SRC/ucx"
  fi
  cd "$SRC/ucx"
  ./autogen.sh
  LDFLAGS="-L$CUDA_SHIM -L$CUDA_HOME/lib64/stubs ${LDFLAGS:-}" ./contrib/configure-release-mt \
    --prefix="$UCX_PREFIX" \
    --enable-shared --disable-static --disable-doxygen-doc \
    --enable-optimizations --enable-cma --enable-devel-headers \
    --with-cuda="$CUDA_HOME" \
    --without-gdrcopy --without-verbs --without-rdmacm \
    --without-knem --without-xpmem
  make -j"$(nproc)"
  make -j"$(nproc)" install-strip
  echo "$UCX_BRANCH" > "$UCX_PREFIX/.ref"
  cd "$ROOT"
fi
log "UCX CUDA transports:"
"$UCX_PREFIX/bin/ucx_info" -v | head -3 || true
if ! "$UCX_PREFIX/bin/ucx_info" -d | grep -E "Transport: *(cuda_copy|cuda_ipc)" | sort -u; then
  echo "WARNING: no cuda_* transports found; UCX was built without CUDA"
fi

# ---------- 6) Abseil (must match what NIXL is compiled against) ----------
if [[ "$(cat "$ABSL_PREFIX/.tag" 2>/dev/null || true)" != "$ABSL_TAG" ]]; then
  log "Abseil tag changed/missing -> rebuilding Abseil and NIXL"
  rm -rf "$ABSL_PREFIX" "$NIXL_PREFIX" "$SRC/abseil-cpp" "$SRC/nixl/build"
fi
if [[ ! -f "$ABSL_PREFIX/lib/pkgconfig/absl_log.pc" ]]; then
  git clone --depth 1 --branch "$ABSL_TAG" https://github.com/abseil/abseil-cpp.git "$SRC/abseil-cpp"
  cmake -S "$SRC/abseil-cpp" -B "$SRC/abseil-cpp/build" -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$ABSL_PREFIX" \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DABSL_PROPAGATE_CXX_STD=ON \
    -DABSL_BUILD_TESTING=OFF \
    -DABSL_ENABLE_INSTALL=ON
  cmake --build "$SRC/abseil-cpp/build" -j"$(nproc)"
  cmake --install "$SRC/abseil-cpp/build"
  echo "$ABSL_TAG" > "$ABSL_PREFIX/.tag"
fi
export PKG_CONFIG_PATH="$ABSL_PREFIX/lib/pkgconfig:$UCX_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
export CMAKE_PREFIX_PATH="$ABSL_PREFIX:${CMAKE_PREFIX_PATH:-}"
export CPLUS_INCLUDE_PATH="$ABSL_PREFIX/include:${CPLUS_INCLUDE_PATH:-}"
export LD_LIBRARY_PATH="$ABSL_PREFIX/lib:${LD_LIBRARY_PATH:-}"

# ---------- 7) NIXL (UCX plugin only) ----------
if [[ ! -f "$NIXL_PREFIX/lib/libnixl.so" ]]; then
  if [[ ! -d "$SRC/nixl/.git" ]]; then
    git clone --depth 1 https://github.com/ai-dynamo/nixl.git "$SRC/nixl"
  fi
  cd "$SRC/nixl"
  rm -rf build

  MESON_ARGS=(--prefix="$NIXL_PREFIX" --libdir=lib --buildtype=release -Ducx_path="$UCX_PREFIX")
  add_opt() { grep -q "'$1'" meson_options.txt 2>/dev/null && MESON_ARGS+=("-D$1=$2") || log "meson option '$1' not found, skipping"; }
  add_opt install_headers true
  add_opt disable_gds_backend true
  add_opt enable_plugins UCX

  meson setup build "${MESON_ARGS[@]}"
  ninja -C build
  ninja -C build install
  cd "$ROOT"
fi

PLUGIN_SO="$(find "$NIXL_PREFIX" -name 'libplugin_UCX.so' | head -1)"
test -n "$PLUGIN_SO" || { echo "ERROR: UCX plugin not built"; exit 1; }
NIXL_PLUGIN_DIR="$(dirname "$PLUGIN_SO")"
log "NIXL plugin: $PLUGIN_SO"
if ldd "$PLUGIN_SO" 2>&1 | grep -q "not found"; then
  echo "ERROR: NIXL plugin has unresolved deps:"
  ldd "$PLUGIN_SO" | grep "not found"
  exit 1
fi
ldd "$PLUGIN_SO" | grep -E "absl_base|libucp" || true

write_env_sh "$NCCL_ROOT" "$NIXL_PLUGIN_DIR"
# shellcheck disable=SC1091
source "$DEPS/env.sh"
log "wrote $DEPS/env.sh"

# ---------- 8) Project ----------
rm -rf "$BUILD_DIR"
cmake -S "$ROOT" -B "$BUILD_DIR" -G Ninja \
  -DMAMBASERVE_WITH_CUDA=ON \
  -DCMAKE_CUDA_ARCHITECTURES="$CMAKE_CUDA_ARCHITECTURES" \
  -DMAMBASERVE_WITH_NCCL=ON \
  -DMAMBASERVE_WITH_NIXL=ON \
  -DBUILD_BENCHMARKS=ON \
  -DNCCL_ROOT="$NCCL_ROOT" \
  -DNIXL_ROOT="$NIXL_ROOT" \
  -DCMAKE_PREFIX_PATH="$NIXL_ROOT;$NCCL_ROOT;$ABSL_PREFIX"
# shellcheck disable=SC2086
cmake --build "$BUILD_DIR" --target $TARGETS -j"$(nproc)"

# ---------- 9) Smoke ----------
if [[ "$SKIP_SMOKE" == "1" ]]; then
  log "SKIP_SMOKE=1 — done. source $DEPS/env.sh before running benches."
  exit 0
fi

log "NIXL smoke"
for tls in "" "self,tcp,sm,cuda_copy,cuda_ipc" "self,tcp,sm,cuda_copy"; do
  log "UCX_TLS='${tls:-<auto>}'"
  if run_smoke "$tls"; then
    echo "NIXL smoke OK (UCX_TLS='${tls:-<auto>}')"
    head -5 /tmp/nixl_smoke/transport.csv
    log "next: source $DEPS/env.sh"
    exit 0
  fi
done

echo "NIXL smoke FAILED"
echo "Debug:"
echo "  source $DEPS/env.sh"
echo "  NIXL_LOG_LEVEL=TRACE UCX_LOG_LEVEL=info \\"
echo "    $BUILD_DIR/benchmarks/transport_bench --device GPU --backends nixl \\"
echo "    --min-mb 1 --max-mb 1 --iters 1 --warmup 0 --modes uni --out-dir /tmp/nixl_smoke"
exit 1
